name: React CI Pipeline

on:
  push:
    branches: [main]
    branches: [staging]
    branches: [test]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
      

      - name: Build app
        run: npm run build
